/*
# description
DdlSnapshotTests は3DBのDDL生成を突き合わせます（T6）。

`GetSqlColumns` は SQLite / MariaDB(基底) / PostgreSQL で別々に実装されているため、
放っておくと列の採否や並びがずれます。ずれると同じ業務SQLが片方のDBで動かなくなるので、
**同じテーブルから同じ列集合が出ること**をテストで固定します。

照合順序の固定も併せて確認します。MariaDBの既定照合順序は大文字小文字とかなを同一視し、
方言変換では直せない差になるため、テーブル作成時に `utf8mb4_bin` を付ける必要があります。

実DB接続は不要です。DDL生成は型のリフレクションだけで完結するため、
接続を開かないインスタンスから呼べます。
 */
using CvBase;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;

namespace TestSqlDialect;

[TestClass]
public sealed class DdlSnapshotTests {

	/// <summary>接続を開かないダミー接続。DDL生成はリフレクションだけで完結する。</summary>
	static ExDatabase Sqlite() => CvBaseSqlite.ExDatabaseSqlite.GetDbConn(":memory:");
	static ExDatabase Maria() => CvBaseMariadb.ExDatabaseMaria.GetDbConn("Server=localhost;Database=dummy;Uid=u;Pwd=p;", isOpen: false);
	static ExDatabase Postgre() => CvBasePostgre.ExDatabasePostgre.GetDbConn("Host=localhost;Database=dummy;Username=u;Password=p", isOpen: false);

	[TestMethod]
	public void 全テーブルのDDLを3DBで生成できる() {
		Assert.IsTrue(DefineDataTable.TableTypes.Count > 40, $"テーブル数={DefineDataTable.TableTypes.Count}");
		using var sqlite = Sqlite();
		using var maria = Maria();
		using var postgre = Postgre();
		foreach (var type in DefineDataTable.TableTypes) {
			foreach (var db in new[] { sqlite, maria, postgre }) {
				var ddl = db.GetSqlCreateTable(type);
				Assert.IsTrue(ddl.Contains("Create Table IF NOT EXISTS", StringComparison.OrdinalIgnoreCase),
					$"{type.Name} / {db.GetType().Name}: {ddl}");
			}
		}
	}

	/// <summary>
	/// SQLiteだけが持つ既知の余剰列。
	/// <para>
	/// <c>ExDatabaseSqlite.GetSqlColumns</c> は <c>GetProperties()</c> を引数なしで呼ぶため
	/// static プロパティも列として拾う。<c>DerivedJodai.TodaySql</c> は判定日の既定値を返す
	/// SQL式のプロパティで、列としては使われない。稼働中のSQLiteのDDLを変えないため
	/// 修正せず既知の差として許容する（`CREATE TABLE IF NOT EXISTS` なので既存DBには影響しない）。
	/// </para>
	/// </summary>
	static readonly Dictionary<string, string[]> _sqliteOnlyColumns = new() {
		[nameof(DerivedJodai)] = ["TodaySql"],
	};

	[TestMethod]
	public void 列集合が3DBで一致する() {
		using var sqlite = Sqlite();
		using var maria = Maria();
		using var postgre = Postgre();
		var mismatches = new List<string>();
		foreach (var type in DefineDataTable.TableTypes) {
			var sqliteNames = ColumnNames(sqlite, type);
			if (_sqliteOnlyColumns.TryGetValue(type.Name, out var known))
				sqliteNames.ExceptWith(known);
			var mariaNames = ColumnNames(maria, type);
			var postgreNames = ColumnNames(postgre, type);
			if (!sqliteNames.SetEquals(mariaNames))
				mismatches.Add($"{type.Name}: Sqlite/MariaDB 差={Diff(sqliteNames, mariaNames)}");
			if (!sqliteNames.SetEquals(postgreNames))
				mismatches.Add($"{type.Name}: Sqlite/PostgreSQL 差={Diff(sqliteNames, postgreNames)}");
		}
		Assert.AreEqual(0, mismatches.Count, string.Join(" / ", mismatches));
	}

	[TestMethod]
	public void MariaDBの列が0個にならない() {
		// 基底の GetSqlColumns は BindingFlags.Public だけを指定していて何も返らず、
		// MariaDB では列が0個の CREATE TABLE が生成されていた。その回帰を防ぐ。
		using var maria = Maria();
		foreach (var type in DefineDataTable.TableTypes) {
			Assert.IsTrue(maria.GetSqlColumns(type).Count > 2, type.Name);
		}
	}

	[TestMethod]
	public void MariaDBは照合順序をutf8mb4_binに固定する() {
		using var maria = Maria();
		foreach (var type in DefineDataTable.TableTypes) {
			var ddl = maria.GetSqlCreateTable(type);
			StringAssert.Contains(ddl, "DEFAULT CHARSET=utf8mb4", type.Name);
			StringAssert.Contains(ddl, $"COLLATE={CvBaseMariadb.ExDatabaseMaria.RequiredCollation}", type.Name);
		}
	}

	[TestMethod]
	public void SQLiteとPostgreSQLは照合順序の指定を付けない() {
		// SQLiteは既定でBINARY、PostgreSQLはデータベース作成時のロケールで決まる
		using var sqlite = Sqlite();
		using var postgre = Postgre();
		var type = DefineDataTable.TableTypes[0];
		Assert.IsFalse(sqlite.GetSqlCreateTable(type).Contains("COLLATE", StringComparison.OrdinalIgnoreCase));
		Assert.IsFalse(postgre.GetSqlCreateTable(type).Contains("COLLATE", StringComparison.OrdinalIgnoreCase));
	}

	[TestMethod]
	public void 自動採番列の定義がDBごとに正しい() {
		var type = typeof(MasterTokui);
		using var sqlite = Sqlite();
		using var maria = Maria();
		using var postgre = Postgre();
		// SQLiteは既存の生成どおり not null default 0 を挟む形（rowid別名として機能する）
		StringAssert.Contains(sqlite.GetSqlCreateTable(type), "Id INTEGER");
		StringAssert.Contains(sqlite.GetSqlCreateTable(type), "PRIMARY KEY AUTOINCREMENT");
		StringAssert.Contains(maria.GetSqlCreateTable(type), "bigint auto_increment");
		StringAssert.Contains(postgre.GetSqlCreateTable(type), "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
	}

	[TestMethod]
	public void PostgreSQLの列名は小文字になる() {
		using var postgre = Postgre();
		foreach (var column in postgre.GetSqlColumns(typeof(MasterTokui))) {
			var name = column.Split(' ')[0];
			Assert.AreEqual(name.ToLowerInvariant(), name, column);
		}
	}

	/// <summary>DDLの列定義から列名だけを取り出す（比較は大文字小文字を無視）。</summary>
	static HashSet<string> ColumnNames(ExDatabase db, Type type) =>
		new(db.GetSqlColumns(type)
				.Select(c => c.Trim().Split(' ')[0].Trim('"', '`', '[', ']')),
			StringComparer.OrdinalIgnoreCase);

	static string Diff(HashSet<string> left, HashSet<string> right) {
		var onlyLeft = left.Except(right, StringComparer.OrdinalIgnoreCase);
		var onlyRight = right.Except(left, StringComparer.OrdinalIgnoreCase);
		return $"左のみ[{string.Join(",", onlyLeft)}] 右のみ[{string.Join(",", onlyRight)}]";
	}
}
