using CvBase;
using NPoco;
using NPoco.DatabaseTypes;
using Npgsql;
using System.Data;
using System.Data.Common;
using System.Reflection;

namespace CvBasePostgre;

/// <summary>
/// PostgreSQL用のデータベースクラス。
/// NpgsqlおよびPostgreSQL固有の接続・DDL・メタデータ処理はこのプロジェクト内で吸収します。
/// </summary>
/// <remarks>
/// TODO: 現在のCvBase/CvDomainLogic/CvServerには、ifnull、json_extract、json_each、
/// json_set、json_group_array、strftime、sqlite_master、PRAGMAなどのSQLite固有SQLが残っています。
/// PostgreSQLをCvServerの実運用DBとして選択可能にする場合は、SQL文字列を直接置換せず、
/// DB方言サービスまたはExDatabaseの仮想メソッドへ段階的に分離し、SQLiteとPostgreSQLの双方で
/// 同一の業務結果になる統合テストを追加してください。本クラスは接続、NPocoマッピング、DDL、
/// メタデータ操作までを担当し、業務SQL全体の互換性までは保証しません。
/// </remarks>
public sealed class ExDatabasePostgre : ExDatabase {

	const int DefaultStringLength = 255;
	const int DefaultObjectLength = 1000;

	/// <summary>クライアント由来SQLをPostgreSQL方言へ変換する。</summary>
	public override CvBase.Sql.ISqlDialect Dialect => CvBase.Sql.SqlDialects.Postgre;

	public ExDatabasePostgre(DbConnection conn) : this(conn, true) {
	}

	ExDatabasePostgre(DbConnection conn, bool isOpen)
		: base(EnsurePostgreConnection(conn), new CvPostgreSqlDatabaseType(), isOpen) {
		if (isOpen)
			UpdateVersion();
	}

	/// <summary>
	/// 接続文字列からPostgreSQL接続を生成します。
	/// </summary>
	/// <param name="connectionString">Host、Port、Database、Username、Passwordなどを含む接続文字列。</param>
	/// <param name="isOpen">接続を開く場合はtrue。</param>
	public static ExDatabasePostgre GetDbConn(string connectionString, bool isOpen = true) {
		var conn = new NpgsqlConnection(connectionString);
		return new ExDatabasePostgre(conn, isOpen);
	}

	public override void Open() {
		if (Connection is not NpgsqlConnection conn)
			return;
		if (conn.State == ConnectionState.Closed)
			conn.Open();
		UpdateVersion();
	}

	public override void Close() {
		if (Connection is not NpgsqlConnection conn)
			return;
		if (conn.State == ConnectionState.Open) {
			KeepConnectionAlive = false;
			conn.Close();
		}
	}

	public override ExDatabase CloneDb() => GetDbConn(Connection.ConnectionString);

	public override void ChangeTimeout(int timeoutSec) {
		ArgumentOutOfRangeException.ThrowIfNegative(timeoutSec);
		CommandTimeout = timeoutSec;
	}

	public override int UseDatabase(string dbname) =>
		throw new NotSupportedException("PostgreSQLでは接続中のデータベースを変更できません。接続文字列を変更して再接続してください。");

	public override bool IsExistTable(string tableName) {
		if (string.IsNullOrWhiteSpace(tableName))
			return false;

		var (schemaName, unqualifiedTableName) = SplitTableName(tableName);
		if (schemaName == null) {
			return ExecuteScalar<bool>(
				"select exists(select 1 from information_schema.tables where table_schema=current_schema() and table_name=@0)",
				unqualifiedTableName);
		}

		return ExecuteScalar<bool>(
			"select exists(select 1 from information_schema.tables where table_schema=@0 and table_name=@1)",
			schemaName,
			unqualifiedTableName);
	}

	public override List<string> GetSqlColumns(Type classT) {
		var properties = classT.GetProperties(BindingFlags.Public | BindingFlags.Instance);
		var orderedProperties = properties
			.OrderBy(static property => property.Name == "Id" ? 0 : property.Name == "Vdc" ? 1 : property.Name == "Vdu" ? 2 : 3)
			.ToList();
		var columns = new List<string>();

		foreach (var property in orderedProperties) {
			if (property.GetCustomAttribute<IgnoreAttribute>() != null
				|| property.GetCustomAttribute<ComputedColumnAttribute>() != null
				|| property.GetCustomAttribute<ResultColumnAttribute>() != null) {
				continue;
			}

			var columnName = property.Name.ToLowerInvariant();
			var sqlType = GetPostgreSqlType(property);
			if (columnName == "id")
				sqlType = "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
			columns.Add($"{columnName} {sqlType}");
		}

		return columns;
	}

	public override int CreateComment(Type classT) {
		var comment = classT.GetCustomAttribute<CommentAttribute>()?.Content;
		if (comment == null)
			return 0;
		return Execute($"COMMENT ON TABLE {QuoteTableName(GetTableName(classT))} IS @0", comment);
	}

	public override string RawExecGetSql(RawExecCmdEnum cmdFlag, string? addSql = null) {
		return cmdFlag switch {
			RawExecCmdEnum.ShowTables => "select table_name from information_schema.tables where table_schema=current_schema() order by table_name",
			RawExecCmdEnum.Analyze => $"EXPLAIN ANALYZE {addSql}",
			RawExecCmdEnum.AnalyzeJ => $"EXPLAIN (ANALYZE, FORMAT JSON) {addSql}",
			RawExecCmdEnum.Explain => $"EXPLAIN {addSql}",
			RawExecCmdEnum.ExplainJ => $"EXPLAIN (FORMAT JSON) {addSql}",
			RawExecCmdEnum.Version => "select version()",
			RawExecCmdEnum.Variables => "SHOW ALL",
			_ => ""
		};
	}

	public override List<Tuple<string, string, long>> GetTableCounts(string tableName = "") {
		var sql = """
select t.table_schema, t.table_name,
       coalesce(obj_description((quote_ident(t.table_schema) || '.' || quote_ident(t.table_name))::regclass), '') as table_comment
  from information_schema.tables t
 where t.table_schema=current_schema()
   and t.table_type='BASE TABLE'
   and t.table_name not like 'sys%'
""";
		var args = Array.Empty<object>();
		if (!string.IsNullOrWhiteSpace(tableName)) {
			sql += " and t.table_name=@0";
			args = [NormalizeIdentifier(tableName.Split('.').Last())];
		}
		sql += " order by t.table_name";

		var result = new List<Tuple<string, string, long>>();
		foreach (var row in Fetch<dynamic>(sql, args)) {
			var schemaName = Convert.ToString(row.table_schema) ?? "public";
			var currentTableName = Convert.ToString(row.table_name) ?? "";
			var comment = Convert.ToString(row.table_comment) ?? "";
			var count = ExecuteScalar<long>($"select count(*) from {QuoteIdentifier(schemaName)}.{QuoteIdentifier(currentTableName)}");
			result.Add(Tuple.Create(currentTableName, comment, count));
		}
		return result;
	}

	static DbConnection EnsurePostgreConnection(DbConnection conn) {
		ArgumentNullException.ThrowIfNull(conn);
		if (conn is not NpgsqlConnection)
			throw new ArgumentException("NpgsqlConnectionを指定してください。", nameof(conn));
		return conn;
	}

	void UpdateVersion() {
		if (Connection is NpgsqlConnection conn && conn.State == ConnectionState.Open)
			Version = conn.PostgreSqlVersion.ToString();
	}

	static string GetPostgreSqlType(PropertyInfo property) {
		var size = property.GetCustomAttribute<ColumnSizeDmlAttribute>();
		if (size != null) {
			return size.ColType switch {
				ColumnType.String => $"varchar({size.Size}) NOT NULL DEFAULT ''",
				// SerializedColumnは現状JSON文字列としてパラメーター化されるため、まずtextで互換性を保つ。
				// PostgreSQL固有のJSON演算へ移行する段階で、jsonb化とNpgsql型指定を同時に行う。
				ColumnType.Json => "text NOT NULL DEFAULT ''",
				ColumnType.Enum => "integer NOT NULL DEFAULT 0",
				_ => $"varchar({DefaultObjectLength}) NOT NULL DEFAULT ''"
			};
		}

		var propertyType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
		if (propertyType == typeof(bool))
			return "boolean NOT NULL DEFAULT FALSE";
		if (propertyType == typeof(byte) || propertyType == typeof(short) || propertyType == typeof(sbyte))
			return "smallint NOT NULL DEFAULT 0";
		if (propertyType == typeof(int) || propertyType == typeof(ushort))
			return "integer NOT NULL DEFAULT 0";
		if (propertyType == typeof(long) || propertyType == typeof(uint))
			return "bigint NOT NULL DEFAULT 0";
		if (propertyType == typeof(ulong))
			return "numeric(20,0) NOT NULL DEFAULT 0";
		if (propertyType == typeof(decimal))
			return "numeric(14,8) NOT NULL DEFAULT 0";
		if (propertyType == typeof(double))
			return "double precision NOT NULL DEFAULT 0";
		if (propertyType == typeof(float))
			return "real NOT NULL DEFAULT 0";
		if (propertyType == typeof(char))
			return "varchar(1) NOT NULL DEFAULT ''";
		if (propertyType == typeof(string))
			return $"varchar({DefaultStringLength}) NOT NULL DEFAULT ''";
		if (propertyType.IsGenericType && propertyType.GetGenericTypeDefinition() == typeof(List<>))
			return "text NOT NULL DEFAULT ''";
		return $"varchar({DefaultObjectLength}) NOT NULL DEFAULT ''";
	}

	static (string? SchemaName, string TableName) SplitTableName(string tableName) {
		var names = tableName.Split('.', 2, StringSplitOptions.TrimEntries);
		return names.Length == 2
			? (NormalizeIdentifier(names[0]), NormalizeIdentifier(names[1]))
			: (null, NormalizeIdentifier(names[0]));
	}

	static string QuoteTableName(string tableName) =>
		string.Join('.', tableName.Split('.', StringSplitOptions.TrimEntries).Select(QuoteIdentifier));

	static string QuoteIdentifier(string identifier) =>
		$"\"{NormalizeIdentifier(identifier).Replace("\"", "\"\"")}\"";

	static string NormalizeIdentifier(string identifier) => identifier.Trim('"').ToLowerInvariant();
}

/// <summary>
/// NPocoが生成する引用識別子を小文字へ統一します。
/// 既存の手書きSQLは識別子を引用していないため、PostgreSQLの小文字化規則と物理名を一致させます。
/// </summary>
sealed class CvPostgreSqlDatabaseType : PostgreSQLDatabaseType {

	public override string EscapeSqlIdentifier(string str) => base.EscapeSqlIdentifier(str.ToLowerInvariant());

	public override string EscapeTableName(string tableName) =>
		string.Join('.', tableName.Split('.', StringSplitOptions.TrimEntries).Select(EscapeSqlIdentifier));
}
